resources:
  - url: http://127.0.0.1:5000/fan-card.js
    type: module
views:
  - cards:
      - type: custom:fab-card
        name: Fan Card Development
        entity: sun.sun
        test_gui: true
